sudo: required
language: bash

services:
  - docker

script:
  - bash generate_config_files.sh

after_script:
  - docker build -t souravmondal10/datastore .

after_success:
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push souravmondal10/datastore
